[build]
  base = "."
  command = "npm run build:web"
  publish = "apps/web/.next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

# Ignore changes in admin directory for web deployment
[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production]
  command = "npm run build:web"

[context.branch-deploy]
  command = "npm run build:web"

# Ignore rules for web deployment
[ignore]
  files = [
    "apps/admin/**/*",
    "packages/**/*",
    "!apps/web/**/*"
  ]

# Admin site configuration
[context.admin]
  command = "npm run build:admin"
  publish = "apps/admin/.next"

[context.admin.environment]
  NEXT_TELEMETRY_DISABLED = "1"

# Ignore rules for admin deployment
[context.admin.ignore]
  files = [
    "apps/web/**/*",
    "packages/**/*",
    "!apps/admin/**/*"
  ] 