[build]
  base = ""
  publish = ""
  command = ""

[context.web]
  command = "npm run build:web"
  publish = "apps/web/.next"
  base = ""
  functions = "apps/web/netlify/functions"
  ignore = "git diff --quiet HEAD^ HEAD -- apps/web packages"

[context.admin]
  command = "npm run build:admin"
  publish = "apps/admin/.next"
  base = ""
  functions = "apps/admin/netlify/functions"
  ignore = "git diff --quiet HEAD^ HEAD -- apps/admin packages"

[context.production]
  command = ""
  publish = ""
  base = ""

[context.production.web]
  command = "npm run build:web"
  publish = "apps/web/.next"
  base = ""
  functions = "apps/web/netlify/functions"

[context.production.admin]
  command = "npm run build:admin"
  publish = "apps/admin/.next"
  base = ""
  functions = "apps/admin/netlify/functions"
