[build]
  base = "apps/admin"
  command = """
    cd ../.. &&
    npm install &&
    cd packages/ui &&
    npm run build &&
    cd ../../ &&
    npm run build:admin
    """
  publish = ".next"

[build.environment]
  NETLIFY_USE_YARN = "false"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[functions]
  directory = "netlify/functions" 